default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: <%= ENV['BD_LOCAL_USER'] %>
  password: <%= ENV['BD_LOCAL_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cracken_development


test:
  <<: *default
  database: cracken_test


production:
  <<: *default
  database: cracken_production
  # username: cracken
  # password: <%= ENV['CRACKEN_DATABASE_PASSWORD'] %>
